export const ADD_MESSAGE = 'ADD_MESSAGE';
export const REGISTER = 'REGISTER';
export const REGISTERED = 'REGISTERED';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const MESSAGE_UNDO = 'MESSAGE_UNDO';
